/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  
  // functions: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'functions',
  //   },
  // ],
};

module.exports = sidebars;
