/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  dev: [
    {
      type: 'autogenerated',
      dirName: 'development',
    },
  ],
  
  functions: [
    {
      type: 'autogenerated',
      dirName: 'functions',
    },
  ],

  help: [
    {
      type: 'autogenerated',
      dirName: 'help',
    },
  ],
};

module.exports = sidebars;
